import Link from "next/link";
import type { Metadata } from "next";
import { Check, Mail, MapPin, Phone } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Separator } from "@/components/ui/separator";
import { getAgencyById, getTripBySlug } from "@/lib/mock-data";
import { formatDateRange, formatPrice } from "@/lib/format";

export const metadata: Metadata = {
  title: "Réservation confirmée | MaghrebVoyage",
  robots: { index: false },
};

/**
 * Mock only. In production the code is generated by the Stripe webhook at
 * confirmation time and read back from the Booking row — never minted in the
 * browser, and never derived from the session id.
 */
function mockConfirmationCode() {
  return `MV-${Math.floor(100000 + Math.random() * 900000)}`;
}

export default async function BookingSuccessPage({ searchParams }: PageProps<"/booking/success">) {
  const params = await searchParams;
  const tripSlug = typeof params.trip === "string" ? params.trip : undefined;
  const seats = typeof params.seats === "string" ? Math.max(Number(params.seats) || 1, 1) : 1;
  const clientName = typeof params.name === "string" ? params.name : undefined;

  const trip = tripSlug ? getTripBySlug(tripSlug) : undefined;
  const agency = trip ? getAgencyById(trip.agencyId) : undefined;
  const confirmationCode = mockConfirmationCode();

  if (!trip) {
    return (
      <div className="mx-auto max-w-lg px-4 py-24 text-center sm:px-6">
        <h1 className="font-heading text-2xl font-bold">Réservation introuvable</h1>
        <p className="mt-2 text-muted-foreground">
          Nous n&apos;avons pas retrouvé cette réservation. Vérifiez votre email de confirmation.
        </p>
        <Button className="mt-6" asChild>
          <Link href="/voyages">Voir les voyages</Link>
        </Button>
      </div>
    );
  }

  const depositPaid = trip.depositAmount * seats;
  const balanceDue = trip.totalPrice * seats - depositPaid;

  return (
    <div className="mx-auto max-w-5xl px-4 py-14 sm:px-6">
      <div className="grid gap-6 lg:grid-cols-5">
        {/* Confirmation */}
        <Card className="gap-0 p-8 text-center lg:col-span-3">
          <span className="mx-auto flex size-16 items-center justify-center rounded-full bg-success">
            <Check className="size-8 text-success-foreground" strokeWidth={3} />
          </span>

          <h1 className="mt-5 font-heading text-2xl font-extrabold tracking-tight">
            {clientName ? `Merci ${clientName}, c'est confirmé !` : "Réservation confirmée !"}
          </h1>
          <p className="mt-2 text-muted-foreground">Votre acompte a été payé avec succès.</p>

          <div className="mt-7 rounded-2xl border-2 border-dashed border-success/40 bg-success-muted/50 p-6">
            <p className="text-xs font-semibold tracking-widest text-muted-foreground uppercase">
              Votre code de confirmation
            </p>
            <p className="mt-2 font-heading text-3xl font-extrabold tracking-wider text-success sm:text-4xl">
              {confirmationCode}
            </p>
            <p className="mt-3 text-sm text-muted-foreground">
              Un email de confirmation vient de vous être envoyé. Il contient également votre lien
              d&apos;annulation.
            </p>
          </div>

          {agency && (
            <div className="mt-7 rounded-2xl border p-5 text-left">
              <p className="text-sm font-semibold">Besoin d&apos;aide ?</p>
              <p className="mt-1 text-sm text-muted-foreground">
                Contactez directement {agency.name}, votre agence organisatrice.
              </p>
              <div className="mt-3 space-y-1.5 text-sm">
                <a
                  href={`mailto:${agency.contactEmail}`}
                  className="flex items-center gap-2 text-primary hover:underline"
                >
                  <Mail className="size-4" />
                  {agency.contactEmail}
                </a>
                <a
                  href={`tel:${agency.contactPhone}`}
                  className="flex items-center gap-2 text-primary hover:underline"
                >
                  <Phone className="size-4" />
                  {agency.contactPhone}
                </a>
              </div>
            </div>
          )}

          <div className="mt-7 flex flex-col gap-3 sm:flex-row sm:justify-center">
            <Button asChild>
              <Link href={`/trip/${trip.slug}`}>Voir le voyage</Link>
            </Button>
            <Button variant="outline" asChild>
              <Link href="/voyages">Voir d&apos;autres voyages</Link>
            </Button>
          </div>
        </Card>

        {/* Recap */}
        <Card className="gap-0 p-6 lg:col-span-2 lg:self-start">
          <h2 className="font-heading text-lg font-bold">Récapitulatif de votre réservation</h2>

          <dl className="mt-5 space-y-3 text-sm">
            <Row label="Voyage" value={trip.title} />
            <Row label="Destination" value={trip.destination} />
            <Row label="Dates" value={formatDateRange(trip.startDate, trip.endDate)} />
            <Row label="Participants" value={`${seats} personne${seats > 1 ? "s" : ""}`} />
            {trip.meetingPoint && (
              <div className="flex items-start justify-between gap-4">
                <dt className="shrink-0 text-muted-foreground">Rendez-vous</dt>
                <dd className="flex items-start gap-1.5 text-right font-medium">
                  <MapPin className="mt-0.5 size-3.5 shrink-0 text-muted-foreground" />
                  {trip.meetingPoint}
                </dd>
              </div>
            )}
          </dl>

          <Separator className="my-5" />

          <dl className="space-y-3 text-sm">
            <div className="flex items-center justify-between gap-4">
              <dt className="text-muted-foreground">Acompte payé</dt>
              <dd className="font-semibold tabular-nums text-success">{formatPrice(depositPaid)}</dd>
            </div>
            <div className="flex items-center justify-between gap-4">
              <dt className="text-muted-foreground">Reste à régler sur place</dt>
              <dd className="font-semibold tabular-nums">{formatPrice(balanceDue)}</dd>
            </div>
          </dl>

          {agency && (
            <>
              <Separator className="my-5" />
              <div className="flex items-center gap-3">
                <span className="flex size-10 shrink-0 items-center justify-center rounded-full bg-accent font-heading text-sm font-bold text-primary">
                  {agency.name.slice(0, 1)}
                </span>
                <div className="min-w-0">
                  <p className="text-xs text-muted-foreground">Organisé par</p>
                  <p className="truncate font-semibold">{agency.name}</p>
                </div>
              </div>
            </>
          )}
        </Card>
      </div>
    </div>
  );
}

function Row({ label, value }: { label: string; value: string }) {
  return (
    <div className="flex items-start justify-between gap-4">
      <dt className="shrink-0 text-muted-foreground">{label}</dt>
      <dd className="text-right font-medium">{value}</dd>
    </div>
  );
}
